In [1]:
import numpy as np

# ARRAY OPERATIONS
# ARRAY WITH CONSTANT

# ARITHMATIC OPERATOR

In [2]:
arr1=np.array([10,20,30,40])
print(arr1)
print(arr1 + 2)
print(arr1 - 2)
print(arr1 * 2)
print(arr1 / 2)
print(arr1 // 2)
print(arr1 ** 2)
print(arr1 % 2)

[10 20 30 40]
[12 22 32 42]
[ 8 18 28 38]
[20 40 60 80]
[ 5. 10. 15. 20.]
[ 5 10 15 20]
[ 100  400  900 1600]
[0 0 0 0]


# RELATIONAL OPERATOR

In [3]:
arr1= np.array([1,10,2,4])
print(arr1 < 2)
print(arr1 > 2)
print(arr1 >= 2)
print(arr1 <= 2)
print(arr1 == 2)
print(arr1 != 2)

[ True False False False]
[False  True False  True]
[False  True  True  True]
[ True False  True False]
[False False  True False]
[ True  True False  True]


# LOGICAL OPERATOR

In [4]:
arr1= np.array([1,10,2,4])
print(arr1 & 2)
print(arr1 | 2)
print(arr1 ^ 2)
print(arr1 << 2)
print(arr1 >> 2)
print(~arr1)
print(2 not in arr1)
print(4 in arr1)

[0 2 2 0]
[ 3 10  2  6]
[3 8 0 6]
[ 4 40  8 16]
[0 2 0 1]
[ -2 -11  -3  -5]
False
True


# ARRAY WITH ARRAY

In [ ]:
arr3=np.array([10,20,30,40])
arr4=np.array([1,2,3,4])
#ARITHMATIC OPERATOR
print(arr3 + arr4)
print(arr3 - arr4)
print(arr3 * arr4)
print(arr3 / arr4)
print(arr3 // arr4)
print(arr3 ** arr4)
print(arr3 % arr4)
#RELATIONAL OPERATOR
print(arr3 == arr4)
print(arr3 != arr4)
print(arr3 < arr4)
print(arr3 > arr4)
print(arr3 <= arr4)
print(arr3 >= arr4)
#LOGICAL OPERATOR
print(arr3 & arr4)
print(arr3 | arr4)
print(arr3 ^ arr4)
print(arr3 << arr4)
print(arr3 >> arr4)
arr5=np.array([1,2])
print(arr4 + arr3)
b=arr3=arr4
print(b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[10 10 10 10]
[     10     400   27000 2560000]
[0 0 0 0]
[False False False False]
[ True  True  True  True]
[False False False False]
[ True  True  True  True]
[False False False False]
[ True  True  True  True]
[0 0 2 0]
[11 22 31 44]
[11 22 29 44]
[ 20  80 240 640]
[5 5 3 2]
[11 22 33 44]
[1 2 3 4]


# NUMPY METHODS
ZEROS
ONES
FULL
EYE
ARANGE
LINSPACE

# NP.ZEROS

In [6]:
arr1=np.zeros((3,2))
print(arr1)
arr2=np.zeros(shape=(3,2))
print(arr2)
arr3=np.zeros(shape=(3,2,4),dtype=int)
print(arr3)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]


# NP.ONES

In [7]:
arr1=np.ones((4,2))
print(arr1)
arr2=np.ones((1,4,3),dtype=bool)
print(arr2)
arr3=np.ones((3,3),dtype=complex)
print(arr3)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


# NP.FULL

In [8]:
ar1=np.full((3,3),fill_value=5)
print(ar1)
ar2=np.full((4,2,3),fill_value=88,dtype=complex)
print(ar2)
print(ar1.shape)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[[88.+0.j 88.+0.j 88.+0.j]
  [88.+0.j 88.+0.j 88.+0.j]]

 [[88.+0.j 88.+0.j 88.+0.j]
  [88.+0.j 88.+0.j 88.+0.j]]

 [[88.+0.j 88.+0.j 88.+0.j]
  [88.+0.j 88.+0.j 88.+0.j]]

 [[88.+0.j 88.+0.j 88.+0.j]
  [88.+0.j 88.+0.j 88.+0.j]]]
(3, 3)


# NP.EYE

In [9]:
ar1=np.eye(3,3)
arr1=np.eye(3,4)
ar2=np.eye(3,5,-2,dtype=bool)
arr2=np.eye(3)
arr3=np.eye(3,3,2,dtype=int)
arr4=np.eye(4,5,5,dtype=complex)
print(arr2)
print(ar1)
print(arr1)
print(ar2)
print(arr3)
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[False False False False False]
 [False False False False False]
 [ True False False False False]]
[[0 0 1]
 [0 0 0]
 [0 0 0]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


# NP.ARANGE

In [10]:
f1=np.arange(1,6)
print(f1)
f2=np.arange(2,11,2)
print(f2)
f3=np.arange(6,dtype=float)
print(f3)
f4=np.arange(2.01,11.5,2.01)
print(f4)

[1 2 3 4 5]
[ 2  4  6  8 10]
[0. 1. 2. 3. 4. 5.]
[ 2.01  4.02  6.03  8.04 10.05]


# NP.LINSPACE

In [11]:
arr1=np.linspace(2,100)
print(arr1)
arr2=np.linspace(4,12,25)
print(arr2)
arr3=np.linspace(2,10,endpoint=False)
print(arr3)
arr4=np.linspace(2,10,num=5,retstep=True)
print(arr4)
ar2=np.linspace(2,50,5,retstep=True)
print(ar2)

[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.  28.
  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.
  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.  84.
  86.  88.  90.  92.  94.  96.  98. 100.]
[ 4.          4.33333333  4.66666667  5.          5.33333333  5.66666667
  6.          6.33333333  6.66666667  7.          7.33333333  7.66666667
  8.          8.33333333  8.66666667  9.          9.33333333  9.66666667
 10.         10.33333333 10.66666667 11.         11.33333333 11.66666667
 12.        ]
[2.   2.16 2.32 2.48 2.64 2.8  2.96 3.12 3.28 3.44 3.6  3.76 3.92 4.08
 4.24 4.4  4.56 4.72 4.88 5.04 5.2  5.36 5.52 5.68 5.84 6.   6.16 6.32
 6.48 6.64 6.8  6.96 7.12 7.28 7.44 7.6  7.76 7.92 8.08 8.24 8.4  8.56
 8.72 8.88 9.04 9.2  9.36 9.52 9.68 9.84]
(array([ 2.,  4.,  6.,  8., 10.]), np.float64(2.0))
(array([ 2., 14., 26., 38., 50.]), np.float64(12.0))


# RANDOM METHODS
RANDOM
RAND
RANDN
RANDINT
SEED
CHOICE

In [12]:
import numpy.random as nr
arr1=nr.random([3,4])
ar2=nr.randn()
print(ar2)
print(arr1)

0.9701266535680763
[[0.51419194 0.64812568 0.28094701 0.36828476]
 [0.76483294 0.88305017 0.45875355 0.50939215]
 [0.12050136 0.79548007 0.20666293 0.772567  ]]


# RANDOM

In [13]:
import numpy.random as nr
a1=nr.random( )
print(a1)
a2=nr.random(2)
print(a2)
a3=nr.random((3,2))
print(a3)
a4=nr.random((4,3,2))
print(a4)

0.294203434173701
[0.18885992 0.01553771]
[[0.34840214 0.7576144 ]
 [0.25286711 0.64024085]
 [0.9027633  0.51308178]]
[[[0.0298759  0.74948594]
  [0.19616186 0.51717015]
  [0.31252456 0.39805246]]

 [[0.70188959 0.32507548]
  [0.8310473  0.74513378]
  [0.84549628 0.6025457 ]]

 [[0.86354311 0.61308119]
  [0.30805709 0.25434326]
  [0.27762257 0.12108392]]

 [[0.61636464 0.72980761]
  [0.90565147 0.47304931]
  [0.7231036  0.66723668]]]


# RAND

In [14]:
import numpy.random as nr
a1=nr.rand()
print(a1)
a2=nr.rand(3)
print(a2)
a3=nr.rand(3,2)
print(a3)
a4=nr.rand(4,6)
print(a4)

0.191890962841608
[0.69868954 0.8315633  0.19857035]
[[0.12406277 0.97548464]
 [0.63759527 0.50485478]
 [0.40706567 0.81389077]]
[[0.46372622 0.25318718 0.54100843 0.07431234 0.6986354  0.49595969]
 [0.21513076 0.18366127 0.77366833 0.55599948 0.62065352 0.34748617]
 [0.13898803 0.21346288 0.43674838 0.75286405 0.61933621 0.10461502]
 [0.66901953 0.69709586 0.24951409 0.71381451 0.53792437 0.34678012]]


# RANDN

In [15]:
import numpy.random as nr
a1=nr.randn()
print(a1)
a2=nr.randn(3)
print(a2)
a3=nr.randn(9)
print(a3)
a4=nr.randn(3,2)
print(a4)
a5=nr.randn(5,4,2)
print(a5)

-3.3671291466131783
[-0.88554255 -0.80004574  0.84578746]
[ 0.27370095  0.91554794 -0.52470413 -0.40250902  1.57005126 -0.06645505
 -2.71838516 -1.12090838  0.29251482]
[[-0.00626171  0.42584249]
 [ 0.52380274  2.46563846]
 [ 1.16718616  0.26412519]]
[[[-0.2419083   0.88370731]
  [ 0.70325132  1.25973213]
  [ 1.89936218  0.68571004]
  [-1.32991815  1.31136622]]

 [[-0.64504238 -1.15263749]
  [ 0.10063942 -0.76378523]
  [ 1.57157759  0.10484889]
  [ 0.15637421 -0.33037393]]

 [[ 0.10306116 -0.79319979]
  [-0.5061709  -0.3852426 ]
  [-1.11435892  0.65914294]
  [-0.76041595 -0.08963365]]

 [[ 0.22155081 -0.92230503]
  [-0.00609859 -0.41896794]
  [-0.57836249  0.3031405 ]
  [ 0.22965023  0.08952931]]

 [[ 0.63686727 -0.29554138]
  [ 0.16922207 -0.0222507 ]
  [ 0.29367389  1.44917875]
  [-0.85766522  0.62312606]]]


# RANDINT

In [16]:
import numpy.random as nr
a1=nr.randint(5)
print(a1)
a2=nr.randint(10,20,5)
print(a2)
a3=nr.randint(10.5,20.5,5)
print(a3)
a4=nr.randint(22,45,(3,5))
print(a4)
a5=nr.randint(20)
print(a5)
# a6=nr.randint() #TypeError: randint() takes at least 1 positional argument (0 given)
# print(a6)

0
[19 19 17 18 19]
[19 19 10 18 13]
[[33 27 35 22 38]
 [37 36 44 31 39]
 [35 32 27 28 25]]
16


# SEED

In [17]:
import numpy.random as nr
a1=nr.seed(0)
print(a1)
nr.seed(0)
a2=nr.randint(100,200,5)
print(a2)
nr.seed(45)
a3=nr.randint(100,200,5)
print(a3)
nr.seed(10)
a4=nr.randn(3,5)
print(a4)
a5=nr.rand(3,2)
print(a5)
nr.seed(10)
a6=nr.random((3,2))
print(a6)

None
[144 147 164 167 167]
[175 130 103 132 195]
[[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597]
 [-0.72008556  0.26551159  0.10854853  0.00429143 -0.17460021]
 [ 0.43302619  1.20303737 -0.96506567  1.02827408  0.22863013]]
[[0.54254437 0.14217005]
 [0.37334076 0.67413362]
 [0.44183317 0.43401399]]
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]]


# CHOICE

In [18]:
import numpy as np
import numpy.random as nr
arr1=np.array(['pen','chair','book','bench'])
c1=nr.choice(arr1)
print(c1)
c2=nr.choice(arr1,(3,2))
print(c2)
# c3=nr.choice(arr1,5,replace=False)
# print(c3)
c3=nr.choice(arr1,5)
print(c3)

chair
[['book' 'pen']
 ['chair' 'pen']
 ['book' 'pen']]
['book' 'pen' 'bench' 'pen' 'pen']
