# NUMPY METHODS TO MODIFY AN EXISTING ARRAY
RAVEL
RESHAPE
CONCATENATE
hSTACK
vSTACK
SPLIT
TILE
REPEAT
SWAPAXES
TRANSPOSE
**RRChvSTRST**

# RAVEL

In [1]:
import numpy as np
a1=np.array([[10,20],[30,40]])
a2=np.ravel(a1)
print(a2)
a3=np.array(10)
a4=np.ravel(a3)
print(a4)

[10 20 30 40]
[10]


# RESHAPE

In [ ]:
a1=np.array([[10,20],[30,40]])
a2=np.reshape(a1,(1,4))
a3=np.reshape(a1,(2,2))
a4=np.reshape(a1,(4,1))
print(a4)
print(a3)
print(a2)

a1=np.array([[10,20,1],[30,40,2],[50,60,3],[70,80,4]])
a2=np.reshape(a1,(4,3))
a3=np.reshape(a1,(2,2,3))
a4=np.reshape(a1,(3,2,2))
print(a1.shape)
print(a2)
print(a3)
print(a4)

a1=np.array([[10,20],[30,40]])
a2=np.reshape(a1,shape=-1)
#print(a1)
print(a2)

# CONCATENATE

In [2]:
a1=np.arange(10,50,10).reshape((2,2))
print(a1)
a2=np.arange(11,51,10).reshape((2,2))
print(a2)
a3=np.concatenate((a1,a2))
a4=np.concatenate((a1,a2),axis=1)
print(a3)
print(a4)

a1=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
a2=np.array([[[11,21],[31,41]],[[51,61],[71,81]]])
a3=np.concatenate((a1,a2))
print(a3)
a4=np.concatenate((a1,a2),axis=1)
print(a4)
a5=np.concatenate((a1,a2),axis=2)
print(a5)

[[10 20]
 [30 40]]
[[11 21]
 [31 41]]
[[10 20]
 [30 40]
 [11 21]
 [31 41]]
[[10 20 11 21]
 [30 40 31 41]]
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]

 [[11 21]
  [31 41]]

 [[51 61]
  [71 81]]]
[[[10 20]
  [30 40]
  [11 21]
  [31 41]]

 [[50 60]
  [70 80]
  [51 61]
  [71 81]]]
[[[10 20 11 21]
  [30 40 31 41]]

 [[50 60 51 61]
  [70 80 71 81]]]


# hSTACK

In [3]:
a1=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
a2=np.array([[[11,21],[31,41]],[[51,61],[71,81]]])
a3=np.hstack((a1,a2))
print(a3)

[[[10 20]
  [30 40]
  [11 21]
  [31 41]]

 [[50 60]
  [70 80]
  [51 61]
  [71 81]]]


# vSTACK

In [4]:
a1=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
a2=np.array([[[11,21],[31,41]],[[51,61],[71,81]]])
a3=np.vstack((a1,a2))
print(a3)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]

 [[11 21]
  [31 41]]

 [[51 61]
  [71 81]]]


# SPLIT

In [5]:
a1=np.array([10,20,30,40,50,60])
a2=np.split(a1,2)
a3=np.split(a1,(3,4))
print(a2)
print(a3)
a4=np.split(a1,(2,3))
print(a4)
a5=np.split(a1,(2,4))
print(a5)

[array([10, 20, 30]), array([40, 50, 60])]
[array([10, 20, 30]), array([40]), array([50, 60])]
[array([10, 20]), array([30]), array([40, 50, 60])]
[array([10, 20]), array([30, 40]), array([50, 60])]


# TILE

In [6]:
import numpy as np
a1=np.array([10,20])
a2=np.tile(a1,2)
print(a2)
a1=np.array([[10,20],[30,40]])
a2=np.tile(a1,2)
a3=np.tile(a1,(2,2))
print(a2)
print(a3)
a1=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
a2=np.tile(a1,(3,2))#blue bracket and elements inside the blue bracket
print(a2)
a3=np.tile(a1,(3,2,1))
print(a3)
a4=np.tile(a1,(2,2,2,1))
print(a4)
a5=np.tile(a1,(2,2,2,1,2))
print(a5)

[10 20 10 20]
[[10 20 10 20]
 [30 40 30 40]]
[[10 20 10 20]
 [30 40 30 40]
 [10 20 10 20]
 [30 40 30 40]]
[[[10 20 10 20]
  [30 40 30 40]
  [10 20 10 20]
  [30 40 30 40]
  [10 20 10 20]
  [30 40 30 40]]

 [[50 60 50 60]
  [70 80 70 80]
  [50 60 50 60]
  [70 80 70 80]
  [50 60 50 60]
  [70 80 70 80]]]
[[[10 20]
  [30 40]
  [10 20]
  [30 40]]

 [[50 60]
  [70 80]
  [50 60]
  [70 80]]

 [[10 20]
  [30 40]
  [10 20]
  [30 40]]

 [[50 60]
  [70 80]
  [50 60]
  [70 80]]

 [[10 20]
  [30 40]
  [10 20]
  [30 40]]

 [[50 60]
  [70 80]
  [50 60]
  [70 80]]]
[[[[10 20]
   [30 40]
   [10 20]
   [30 40]]

  [[50 60]
   [70 80]
   [50 60]
   [70 80]]

  [[10 20]
   [30 40]
   [10 20]
   [30 40]]

  [[50 60]
   [70 80]
   [50 60]
   [70 80]]]


 [[[10 20]
   [30 40]
   [10 20]
   [30 40]]

  [[50 60]
   [70 80]
   [50 60]
   [70 80]]

  [[10 20]
   [30 40]
   [10 20]
   [30 40]]

  [[50 60]
   [70 80]
   [50 60]
   [70 80]]]]
[[[[[10 20 10 20]
    [30 40 30 40]]

   [[50 60 50 60]
    [70 80 70 80]]


# REPEAT

In [10]:
import numpy as np
a1=np.array([10,20])
a2=np.repeat(a1,2)
print(a2)
a1=np.array([[10,20],[30,40]])
a2=np.repeat(a1,2)
print(a2)
# a2=np.repeat(a1,2,axis=0)
# # print(a2)
# a2=np.repeat(a1,2,axis=2)
# # print(a2)

[10 10 20 20]
[10 10 20 20 30 30 40 40]


# SWAPAXES

In [11]:
import numpy as np
a1=np.array([[10,20],[30,40]])
a2=np.swapaxes(a1,axis1=1,axis2=0)
#print(a2)
a1=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
a2=np.swapaxes(a1,axis1=1,axis2=0)
print(a2)
a3=np.swapaxes(a1,axis1=2,axis2=1)
print(a3)
a4=np.swapaxes(a1,axis1=1,axis2=2)
print(a4)
a5=np.swapaxes(a1,axis1=0,axis2=2)
print(a5)

[[[10 20]
  [50 60]]

 [[30 40]
  [70 80]]]
[[[10 30]
  [20 40]]

 [[50 70]
  [60 80]]]
[[[10 30]
  [20 40]]

 [[50 70]
  [60 80]]]
[[[10 50]
  [30 70]]

 [[20 60]
  [40 80]]]


# TRANSPOSE

In [12]:
import numpy as np
a1=np.array([[10,20],[30,40]])
a2=np.transpose(a1,(1,0))
#print(a2)
a1=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
a2=np.transpose(a1,(0,2,1))
print(a2)
a3=np.transpose(a1,(2,1,0))
print(a3)
a4=np.transpose(a1,(1,2,0))
print(a4)
a1=np.array([[10,20,30],[40,50,60]])
a2=np.transpose(a1,(1,0))
print(a2)

[[[10 30]
  [20 40]]

 [[50 70]
  [60 80]]]
[[[10 50]
  [30 70]]

 [[20 60]
  [40 80]]]
[[[10 50]
  [20 60]]

 [[30 70]
  [40 80]]]
[[10 40]
 [20 50]
 [30 60]]
