In [ ]:
#variable=np.array(object,dtype,ndmin,copy)
import numpy as np
a1=np.array([10,20,30,40])
print(a1)


[10 20 30 40]


# attributes of array
ndim
size
dtype
itemsize
nbytes

In [18]:
#ndim
a1=np.array([10,20,30,40])
print(a1.ndim)
a2=np.array([[1,2,3],[4,5,6]])
print(a2.ndim)
a3=np.array(10001)
print(a3.ndim)
#size
print(a1.size)
print(a2.size)
print(a3.size)
#dtype
print(a1.dtype)
a4=np.array([2+3j,8+4j,2-3j])
print(a4.dtype)
a5=np.array([10.25,20])
print(a1.dtype)
#itemsize
print(a4.itemsize)
print(a5.itemsize)
#nbytes
print(a1.nbytes)
print(a4.nbytes)
print(a5.nbytes)




1
2
0
4
6
1
int64
complex128
int64
16
8
32
48
16


In [28]:
arr1= np.array([10,20],dtype=int,ndmin=3)
arr2=np.array(arr1,copy=True)
arr1[0]=100
arr3=np.array(arr1,copy=False)
arr1[0]=945
arr4=np.array(arr1)
arr1[0]=628
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr1.dtype)
print(arr1.itemsize)
print(arr1.nbytes)


[[[628 628]]]
[[[10 20]]]
[[[628 628]]]
[[[945 945]]]
int64
8
16


properties of array over the list
HOD IS FME

# INDEXING

In [29]:
ree=np.array([10,20,30,40])
print(ree[2])#30
print(ree[3])#40
ree1=np.array([[10,20],[30,40]])
print(ree1[1])#[30,40]
print(ree1[1,1])#30
ree2=np.array([[[10,20],[30,40]],[[40,50],[60,70]]])
print(ree2[1,1,1])#70
print(ree2[1,0,1])#50
print(ree2[0,0,0])#10
print(ree2[0,1,1])#40
print(ree2[1,1,0])#60

30
40
[30 40]
40
70
50
10
40
60


# SLICING

In [ ]:
dee=np.array([10,20,30,40])
print(dee[1:3])#[20,30]
print(dee[1:4])#[20,30,40]
print(dee[:])#[10,20,30,40]
dee1=np.array([[10,20,30],[40,50,60]])
print(dee1[::,0])#[10,40]
print(dee1[1])#[40,50,60]
print(dee1[1,2])#[60]
print(dee1[0,2])#30
print(dee1[1,1])#50
print(dee1[1,0])#40
print(dee1[0,1])#20
print(dee1[0,0])#10

[20 30]
[20 30 40]
[10 20 30 40]
[10 40]
[40 50 60]
60
30
50
40
20
10


In [31]:
dee1=np.array([[10,20,30],[40,50,60]])
print(dee1[::,0])#[10,40]
print(dee1[::,2])#[30,60]
print(dee1[::,1])#[20,50]
print(dee1[::,::2])#[[10,30],[40,60]]
print(dee1[::,1::])#[[20,30],[50,60]]

[10 40]
[30 60]
[20 50]
[[10 30]
 [40 60]]
[[20 30]
 [50 60]]


In [ ]:
arr3=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(arr3[::,::,0])#[[10,30],[50,70]]
print(arr3[::,1,::])#[[30,40],[70,80]]
print(arr3[::,0,::])#[[10,20],[50,60]]
print(arr3[::,0])#[[10,20],[30,40]]
print(arr3[0])#[[10,20],[30,40]]
print(arr3[::,1])#[[30,40],[70,80]]
print(arr3[::,0,1])#[20,60]
print(arr3[1,0,0])#50
print(arr3[1,0,1])#60
print(arr3[::,::,-1])#[[60,80],[20,40]]
print(arr3[::,-1,0])#[70,30]
print(arr3[1,::-1,-1])#[80,60]
print(arr3[0,::-1,-2])#[30,10]
print(arr3[1,::-1])#[[70,80],[50,60]]

[[10 30]
 [50 70]]
[[30 40]
 [70 80]]
[[10 20]
 [50 60]]
[[10 20]
 [50 60]]
[[10 20]
 [30 40]]
[[30 40]
 [70 80]]
[20 60]
50
60
[[20 40]
 [60 80]]
[30 70]
[80 60]
[30 10]
[[70 80]
 [50 60]]


In [33]:
arr4=np.array([[[10,20,11],[30,40,12]],[[50,60,13],[70,80,90]]])
print(arr4[::,0,::-2])#[[11,10],[50,13]]
print(arr4[::,-1,::-2])#[[12,30],[90,70]]
print(arr4[0,::,:2:])#[[10,20],[30,40]]

[[11 10]
 [13 50]]
[[12 30]
 [90 70]]
[[10 20]
 [30 40]]
