In [1]:
import numpy as np

# MATHEMATICAL OR STATISTICAL METHODS OF NUMPY
SQRT
EXP
LOG
SUM
PROD
MAX
MIN
MEAN
MEDIAN
PERCENTILE
--------------------------------------
CUMSUM
CUMPROD
VAR
STD
MATMUL
DOT
DET
INV
COPY
VIEW
--------------------------------------
SORT
ARGSORT
UNIQUE
LOGICAL_AND
LOGICAL_OR
LOGICAL_NOT
DELETE
INSERT

SQRT
EXP
LOG
SUM
PROD
MAX
MIN
MEAN
MEDIAN
PERCENTILE

# SQRT,EXP,LOG

In [2]:
a1=np.array([2,4,64])
a2=np.sqrt(a1)
print(a2)
a1=np.array([0,1,2])
a2=np.exp(a1)
print(a2)
a1=np.array([1,2.71828183,7.3890561])
a2=np.log(a1)
print(a2)
a1=np.array([1,58.995,65.8796])
a2=np.log(a1)
print(a2)

[1.41421356 2.         8.        ]
[1.         2.71828183 7.3890561 ]
[0. 1. 2.]
[0.         4.07745269 4.18782883]


# SUM

In [3]:
import numpy as np
a1=np.array([[10,20],[30,40]])
a2=np.sum(a1)
print(a2)
a2=np.sum(a1,keepdims=True)
print(a2)
a2=np.sum(a1,axis=0)
print(a2)
a2=np.sum(a1,axis=1)
print(a2)
a2=np.sum(a1,axis=0,initial=100)
print(a2)
a2=np.sum(a1,axis=1,initial=100)
print(a2)

100
[[100]]
[40 60]
[30 70]
[140 160]
[130 170]


# PROD

In [4]:
a1=np.array([[5,6],[3,4]])
a2=np.prod(a1)
print(a2)
a2=np.prod(a1,keepdims=True)
print(a2)
a2=np.prod(a1,axis=0)
print(a2)
a2=np.prod(a1,axis=1)
print(a2)
a2=np.prod(a1,axis=0,initial=100)
print(a2)
b=np.array([[True,False],[True,True]])
a2=np.prod(a1,axis=1,where=b)
print(a2)

360
[[360]]
[15 24]
[30 12]
[1500 2400]
[ 5 12]


# MAX

In [5]:
a1=np.array([[5,6],[3,4]])
a2=np.max(a1)
print(a2)
a2=np.max(a1,keepdims=True)
print(a2)
a2=np.max(a1,axis=0)
print(a2)
a2=np.max(a1,axis=1)
print(a2)
a2=np.max(a1,axis=0,initial=100)
print(a2)
b=np.array([[True,False],[True,True]])
a2=np.max(a1,axis=1,where=b,initial=2)
print(a2)

6
[[6]]
[5 6]
[6 4]
[100 100]
[5 4]


# MIN

In [6]:
a1=np.array([[5,6],[3,4]])
a2=np.min(a1)
print(a2)
a2=np.min(a1,keepdims=True)
print(a2)
a2=np.min(a1,axis=0)
print(a2)
a2=np.min(a1,axis=1)
print(a2)
a2=np.min(a1,axis=0,initial=100)
print(a2)
b=np.array([[True,False],[True,True]])
a2=np.min(a1,axis=1,where=b,initial=2)
print(a2)

3
[[3]]
[3 4]
[5 3]
[3 4]
[2 2]


# MEAN

In [7]:
import numpy as np
a1=np.array([[10,20],[5,30]])
a2=np.mean(a1)
print(a2)
a3=np.mean(a1,axis=0)
print(a3)
a3=np.mean(a1,axis=0,keepdims=True)
print(a3)
a4=np.mean(a1,axis=1,keepdims=True)
print(a4)
a5=np.mean(a1,axis=0,where=np.array([[True,True],[False,True]]),keepdims=True)
print(a5)
a5=np.mean(a1,axis=1,where=np.array([[True,True],[False,True]]),keepdims=True)
print(a5)
a7=np.array([[10,20,30],[4,5,6],[70,80,90]])
a3=np.mean(a7,axis=0,keepdims=True)
print(a3)
a4=np.mean(a7,axis=1,keepdims=True)
print(a4)

16.25
[ 7.5 25. ]
[[ 7.5 25. ]]
[[15. ]
 [17.5]]
[[10. 25.]]
[[15.]
 [30.]]
[[28. 35. 42.]]
[[20.]
 [ 5.]
 [80.]]


# MEDIAN

In [9]:
import numpy as np
a1=np.array([8,2,1,3,9])
b=np.median(a1)
print(b)
a3=np.median(a1,axis=0,keepdims=True)
print(a3)
a2=np.array([[8,2],[1,3],[9,6]])
a3=np.median(a2,axis=1,keepdims=True)
print(a3)
a3=np.median(a2,axis=0,keepdims=True)
print(a3)
a7=np.array([[10,20,30],[4,5,6],[70,80,90]])
a3=np.median(a7,axis=0,keepdims=True)
print(a3)
a4=np.median(a7,axis=1,keepdims=True)
print(a4)

3.0
[3.]
[[5. ]
 [2. ]
 [7.5]]
[[8. 3.]]
[[10. 20. 30.]]
[[20.]
 [ 5.]
 [80.]]


# PERCENTILE

In [10]:
a1=np.arange(1,11)
b=np.percentile(a1,50)
print(b)
a1=np.array([8,9,7,5,6,1,2,3,4,10])
b=np.percentile(a1,25,overwrite_input=True)
print(b)
a7=np.array([[10,20,30],[4,5,6],[70,80,90]])
a3=np.percentile(a7,50,axis=0)
print(a3)
a4=np.percentile(a7,75,axis=1,keepdims=True)
print(a4)

5.5
3.25
[10. 20. 30.]
[[25. ]
 [ 5.5]
 [85. ]]


CUMSUM
CUMPROD
VAR
STD
MATMUL
DOT
DET
INV
COPY
VIEW

# CUMSUM

In [11]:
import numpy as np
a1=np.arange(1,11)
a2=np.cumsum(a1)
print(a2)
a1=np.array([8,9,7,5,6,1,2,3,4,10])
b=np.cumsum(a1)
print(b)
b=np.cumsum(a1,axis=0)
print(b)
a7=np.array([[10,20,30],[4,5,6],[70,80,90]])
a3=np.cumsum(a7,axis=0)
print(a3)
a4=np.cumsum(a7,axis=1)
print(a4)

[ 1  3  6 10 15 21 28 36 45 55]
[ 8 17 24 29 35 36 38 41 45 55]
[ 8 17 24 29 35 36 38 41 45 55]
[[ 10  20  30]
 [ 14  25  36]
 [ 84 105 126]]
[[ 10  30  60]
 [  4   9  15]
 [ 70 150 240]]


# CUMPROD

In [12]:
import numpy as np
a1=np.arange(1,11)
a2=np.cumprod(a1)
print(a2)
a1=np.array([8,9,7,5,6,1,2,3,4,10])
b=np.cumprod(a1)
print(b)
b=np.cumprod(a1,axis=0)
print(b)
a7=np.array([[10,20,30],[4,5,6],[70,80,90]])
a3=np.cumprod(a7,axis=0)
print(a3)
a4=np.cumprod(a7,axis=1)
print(a4)

[      1       2       6      24     120     720    5040   40320  362880
 3628800]
[      8      72     504    2520   15120   15120   30240   90720  362880
 3628800]
[      8      72     504    2520   15120   15120   30240   90720  362880
 3628800]
[[   10    20    30]
 [   40   100   180]
 [ 2800  8000 16200]]
[[    10    200   6000]
 [     4     20    120]
 [    70   5600 504000]]


# VAR

In [13]:
import numpy as np
a1=np.arange(1,11)
a2=np.var(a1)
print(a2)
a1=np.array([8,9,7,5,6,1,2,3,4,10])
c=np.array([True,True,True,False,True,True,True,True,True,True])
b=np.var(a1,keepdims=True,where=c)
print(b)
b=np.var(a1,axis=0)
print(b)
a7=np.array([[10,20,30],[4,5,6],[70,80,90]])
a3=np.var(a7,axis=0)
print(a3)
a4=np.var(a7,axis=1)
print(a4)

8.25
[9.13580247]
8.25
[ 888. 1050. 1248.]
[66.66666667  0.66666667 66.66666667]


# STD

In [14]:
import numpy as np
a1=np.arange(1,11)
a2=np.std(a1)
print(a2)
a1=np.array([8,9,7,5,6,1,2,3,4,10])
c=np.array([True,True,True,False,True,True,True,True,True,True])
b=np.std(a1,keepdims=True,where=c)
print(b)
b=np.std(a1,axis=0)
print(b)
a7=np.array([[10,20,30],[4,5,6],[70,80,90]])
a3=np.std(a7,axis=0)
print(a3)
a4=np.std(a7,axis=1)
print(a4)

2.8722813232690143
[3.022549]
2.8722813232690143
[29.79932885 32.40370349 35.32704347]
[8.16496581 0.81649658 8.16496581]


# MATMUL

In [15]:
import numpy as np
a1=np.array([[1,2,5],[3,4,1]])
a2=np.array([[5,6],[2,4],[7,2]])
a3=np.matmul(a1,a2)
print(a3)

[[44 24]
 [30 36]]


# DOT

In [16]:
import numpy as np
a1=np.array([[1,2,5],[3,4,1]])
a2=np.array([[5,6],[2,4],[7,2]])
a3=np.dot(a1,a2)
print(a3)

[[44 24]
 [30 36]]


# DET,INV

In [18]:
a1=np.array([[1,2],[5,6]])
d=np.linalg.det(a1)
print(d)
d1=np.linalg.inv(a1)
print(d1)


-3.999999999999999
[[-1.5   0.5 ]
 [ 1.25 -0.25]]


# COPY,VIEW

In [20]:
a1=np.array([1,2,3])
a2=a1.copy()
a1[0]=100
print(a1)
print(a2)
#############################
a3=a1.view()
a1[0]=100
print(a1)
print(a3)

[100   2   3]
[1 2 3]
[100   2   3]
[100   2   3]


# SORT

In [21]:
a1=np.array([1,10,6,2])
a2=np.sort(a1)
print(a2)
print(a2[::-1])
a1=np.array([[1,10,3],[6,2,0]])
a2=np.sort(a1)
print(a2)
a2=np.sort(a1,axis=0)
print(a2)

[ 1  2  6 10]
[10  6  2  1]
[[ 1  3 10]
 [ 0  2  6]]
[[ 1  2  0]
 [ 6 10  3]]


# ARGSORT

In [22]:
a1=np.array([[1,10,3],[6,2,0]])
a2=np.argsort(a1)
print(a2)
a2=np.argsort(a1,axis=0)
print(a2)

[[0 2 1]
 [2 1 0]]
[[0 1 1]
 [1 0 0]]


# UNIQUE

In [26]:
a1=np.array([20,30,10,20,40,30])
a2=np.unique(a1)
print(a2)
a3=np.unique(a1,return_index=True)
print(a3)
a4=np.unique(a1,return_counts=True)
print(a4)
a5=np.unique(a1,return_inverse=True)
print(a5)

[10 20 30 40]
(array([10, 20, 30, 40]), array([2, 0, 1, 4]))
(array([10, 20, 30, 40]), array([1, 2, 2, 1]))
(array([10, 20, 30, 40]), array([1, 2, 0, 1, 3, 2]))


# LOGICAL_AND

In [31]:
a1=np.array([20,30,10,20,40,30])
res=np.logical_and(a1>10,a1<30)
print(res)
print(a1[res])
res=(a1>10) & (a1<30)
print(res)
print(a1[res])
print(a1[[True,False,False,True,False,False]])

[ True False False  True False False]
[20 20]
[ True False False  True False False]
[20 20]
[20 20]


# LOGICAL_OR

In [34]:
a1=np.array([20,30,10,20,40,30])
res=np.logical_or(a1==10,a1==30)
print(res)
print(a1[res])
res=(a1==10)|(a1==30)|(a1==20)
print(res)
print(a1[res])

[False  True  True False False  True]
[30 10 30]
[ True  True  True  True False  True]
[20 30 10 20 30]


# LOGICAL NOT

In [37]:
a1=np.array([20,30,10,20,40,30])
res=np.logical_not(a1>=20)
print(res)
print(a1[res])
res=~(a1>=20)
print(res)
print(a1[res])

[False False  True False False False]
[10]
[False False  True False False False]
[10]


# DELETE

In [39]:
a1=np.array([[10,20],[30,40]])
a2=np.delete(a1,0)#default:axis=none
print(a1)
print(a2)
a1=np.array([[10,20],[30,40]])
a2=np.delete(a1,0,axis=1)
print(a1)
print(a2)
a3=np.delete(a1,0,axis=0)
print(a1)
print(a3)
a2=np.delete(a1,[3,1])
print(a2)

[[10 20]
 [30 40]]
[20 30 40]
[[10 20]
 [30 40]]
[[20]
 [40]]
[[10 20]
 [30 40]]
[[30 40]]
[10 30]


# INSERT

In [42]:
a1=np.array([[10,20],[30,40]])
a2=np.insert(a1,2,[100,200])
print(a1)
print(a2)
# a2=np.insert(a1,2,[100,200],axis=0)
# print(a1)
# print(a2)
a3=np.insert(a1,2,[100,200],axis=1)
print(a1)
print(a3)

[[10 20]
 [30 40]]
[ 10  20 100 200  30  40]
[[10 20]
 [30 40]]
[[ 10  20 100]
 [ 30  40 200]]
