1. Create an array which consists of 50 equally spaced numbers between 2-5.
2. Create an array of 5 random numbers which are uniformly distributed.
3. Create an 2-d array which consists of 1st 10 natural numbers.
4. Create an array of the shape 1x3.
5. Create an array of 1st 50 odd numbers.

In [1]:
import numpy as np

In [2]:
#.1
a1=np.linspace(2,5)
print(a1)
#.2
a1=np.random.rand(5)
print(a1)
#.3
a1=np.arange(1,11)
a2=np.reshape(a1,(2,5))
print(a2)
#.4
a1=np.eye(1,3)
print(a1)
#.5
a1=np.arange(2,100,2)
print(a1)

[2.         2.06122449 2.12244898 2.18367347 2.24489796 2.30612245
 2.36734694 2.42857143 2.48979592 2.55102041 2.6122449  2.67346939
 2.73469388 2.79591837 2.85714286 2.91836735 2.97959184 3.04081633
 3.10204082 3.16326531 3.2244898  3.28571429 3.34693878 3.40816327
 3.46938776 3.53061224 3.59183673 3.65306122 3.71428571 3.7755102
 3.83673469 3.89795918 3.95918367 4.02040816 4.08163265 4.14285714
 4.20408163 4.26530612 4.32653061 4.3877551  4.44897959 4.51020408
 4.57142857 4.63265306 4.69387755 4.75510204 4.81632653 4.87755102
 4.93877551 5.        ]
[0.37807389 0.30934861 0.4425183  0.10969149 0.49620042]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1. 0. 0.]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


6. In an array of the 1st 50 odd numbers, find the 50th percentile element (number)
7. Create a 5 -d array of 1st 3 numbers.
8. A1=array([1,5,10,3,2,6,3,9])
1) create array which are greater than 5
2) find the elements which are less than mean_value
3) find the median of the array
4) reshape it to (2x4)
5) for the reshape array find the commutative sum along the 0th axis.
6) for the array a1 perform element wise addition with array([7]).
9. A2= [[6,7,1],[8,9,3],[2,3,9]]
1) find the transpose of the matrix a2.
2) repeat the array elements individually for 2 times.
3) convert 2-d array a2 to 1-d array.
4) concate the a2 with 3x3 matrix of the even numbers from (1-19) along the axis=1
10. A3=[3,5,1,9,7,2,6,7]
Find the distribution of the data points from the central value and conclude whether the data points are clustered/ variables.

In [13]:
#.6
a1=np.arange(2,100,2)
a2=np.percentile(a1,50)
print(a2)
#.7
a1=np.arange(1,4)
a2=np.array(a1,ndmin=5)
print(a2)
#.8
a1=np.array([1,5,10,3,2,6,3,9])
print(a1[[False,False,True,False,False,True,False,True]])
a2=np.median(a1)
print(a2)
a5=np.mean(a1)
print(a5)
a3=np.reshape(a1,(2,4))
print(a3)
a4=np.cumsum(a3,axis=0)
print(a4)
print(a1+7)
#.9
import numpy as np
a2= np.array([[6,7,1],[8,9,3],[2,3,9]])
a3=np.transpose(a2)
print(a3)
a4=np.repeat(a2,2)
print(a4)
a5=np.ravel(a2)
print(a5)
a6=np.arange(2,20,2)
print(a6)
a7=np.reshape(a6,shape=(3,3))
print(a7)
a8=np.concatenate((a6,a7),axis=1)
print(a8)
#.10
a1=[3,5,1,9,7,2,6,7]
a2=np.std(a1)
print(a2)

50.0
[[[[[1 2 3]]]]]
[10  6  9]
4.0
4.875
[[ 1  5 10  3]
 [ 2  6  3  9]]
[[ 1  5 10  3]
 [ 3 11 13 12]]
[ 8 12 17 10  9 13 10 16]
[[6 8 2]
 [7 9 3]
 [1 3 9]]
[6 6 7 7 1 1 8 8 9 9 3 3 2 2 3 3 9 9]
[6 7 1 8 9 3 2 3 9]
[ 2  4  6  8 10 12 14 16 18]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


AxisError: axis 1 is out of bounds for array of dimension 1